version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql.dev.local
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    networks:
      - dev.local
networks:
  dev.local:
    external: true