version: '2'
services:
  lamp:
#    build:
#      context: ./docker-files/php5
#      dockerfile: Dockerfile
    image: kylephp/alpine-lamp
    container_name: lamp
    volumes:
      - "./html/:/web/html"
    ports:
      - "90:80"
    restart: always
    networks:
      - dev.local
  lamp7:
#    build:
#      context: ./docker-files/php7
#      dockerfile: Dockerfile
    image: kylephp/alpine-lamp:php7
    container_name: lamp7
    volumes:
      - "./html/:/web/html"
    ports:
      - "91:80"
    restart: always
    networks:
      - dev.local
networks:
  dev.local:
    external: true