version: '2'
services:
  lamp:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: kylephp/alpine-lamp
    container_name: lamp
    volumes:
      - "./html/:/web/html"
    links:
      - mysql:mysql.dev.php
    ports:
      - "82:80"
    restart: always
  lamp7:
#    build:
#      context: .
#      dockerfile: Dockerfile7
    image: kylephp/alpine-lamp:php7
    container_name: lamp7
    volumes:
      - "./html/:/web/html"
    links:
      - mysql:mysql.dev.php
    ports:
      - "83:80"
    restart: always
  mysql:
    image: mysql
    container_name: mysql.dev.php
    ports:
      - "4306:3306"
    environment:
      MYSQL_USER: kyle
      MYSQL_PASSWORD: kyle
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always